### 회원가입
POST http://localhost:8080/api/auth/signUp
Content-Type: application/json

{
  "email": "rudeka0706@gmail.com",
  "password": "12345",
  "nickname": "korea",
  "phoneNumber": "010-1234-5678"
}

### 로그인
POST http://localhost:8080/api/auth/signIn
Content-Type: application/json

{
  "email": "testtest4@gmail.com",
  "password": "12345"
}

### 이메일 인증
POST http://localhost:8080/api/auth/mail/certification
Content-Type: application/json

{
  "email": "rudeka0706@naver.com"
}

### 이메일 검증
POST http://localhost:8080/api/auth/mail/verify
Content-Type: application/json

{
  "email": "rudeka0706@naver.com",
  "code": "752733"
}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDM0MDg4MTksInN1YiI6ImFjY2Vzcy10b2tlbiIsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcklkIjoidGVzdHRlc3RAdGVzdC5jb20iLCJleHAiOjE3MDM0MTA2MTl9.75P46IJRFuAD3fr7fjeNjrF2lcOywAhWDOR9RKzXywU"
}

### 토큰 재발급
POST http://localhost:8080/api/auth/reissue-token
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDQ2OTQyMDQsInN1YiI6ImFjY2Vzcy10b2tlbiIsInJvbGUiOiJST0xFX1VTRVIiLCJ1c2VySWQiOiJ0ZXN0dGVzdDRAZ21haWwuY29tIiwiZXhwIjoxNzA0Njk2MDA0fQ.c1nFKaHyH8AC-qLpW9J7tznAMix0qoFl3uyCxaPg5Ok",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDQ2OTQyMDQsInN1YiI6InJlZnJlc2gtdG9rZW4iLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcklkIjoidGVzdHRlc3Q0QGdtYWlsLmNvbSIsImV4cCI6MTcwNTEyNjIwNH0.kZVucnbGhznIarR9IOBlIFSgk7nLuY8bQefNghfzi8M"
}