### 회원가입
POST http://localhost:8080/api/auth/signUp
Content-Type: application/json

{
  "email": "rudeka0706@gmail.com",
  "password": "12345",
  "nickname": "korea",
  "phoneNumber": "010-1234-5678"
}

### 로그인
POST http://localhost:8080/api/auth/signIn
Content-Type: application/json

{
  "email": "testtest@test.com",
  "password": "12345"
}

### 로그인2
POST http://localhost:8080/api/auth/signIn
Content-Type: application/json

{
  "email": "testtest1@test.com",
  "password": "12345"
}

### 이메일 인증
POST http://localhost:8080/api/auth/mail/certification
Content-Type: application/json

{
  "email": "rudeka0706@naver.com"
}

### 이메일 검증
POST http://localhost:8080/api/auth/mail/verify
Content-Type: application/json

{
  "email": "rudeka0706@naver.com",
  "code": "752733"
}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDM0MDg4MTksInN1YiI6ImFjY2Vzcy10b2tlbiIsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcklkIjoidGVzdHRlc3RAdGVzdC5jb20iLCJleHAiOjE3MDM0MTA2MTl9.75P46IJRFuAD3fr7fjeNjrF2lcOywAhWDOR9RKzXywU"
}

### 토큰 재발급
POST http://localhost:8080/api/auth/reissue-token
Content-Type: application/json
accessToken: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDMxNjEzODMsInN1YiI6ImFjY2Vzcy10b2tlbiIsInJvbGUiOiJST0xFX1VTRVIiLCJ1c2VySWQiOiJ0ZXN0MkB0ZXN0LmNvbSIsImV4cCI6MTcwMzE2MzE4M30.S7LtpCPFb3ldxgFhPElwwbgSgSclFe_s31Tk4GrPIYw
refreshToken: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MDMxNjEzODMsInN1YiI6InJlZnJlc2gtdG9rZW4iLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcklkIjoidGVzdDJAdGVzdC5jb20iLCJleHAiOjE3MDM1OTMzODN9.d5PS02TEL2_E4MQVFjFOhPvatEEFkRG20wua6hl9c2U

{

}