spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update    # create, create_drop update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587   #587
    username: gxxk76@gmail.com
    password: qtjkzfkliaofogue
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    header: Authorization
    prefix: Bearer
    secret: 1a9339739d1c6f0df7e32b395fab1206112ec471d496f2ac6695c73d3d8d0d16
    access-token-expire-time: 1800000 # 30분 밀리초
    refresh-token-expire-time: 604800000 # 1주 밀리초